# Generated by Django 3.0.6 on 2020-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QBesharat', '0003_auto_20200626_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10, verbose_name='Sex'),
        ),
    ]
