# Generated by Django 3.0.6 on 2020-06-26 20:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('QBesharat', '0004_auto_20200626_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[150, 150], upload_to='media/', verbose_name='Profile Image'),
        ),
    ]
