# Generated by Django 3.0.6 on 2020-07-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QBesharat', '0008_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['description'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='', max_length=2000, unique=True, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('verse', models.TextField(max_length=2000, unique=True, verbose_name='Verse')),
                ('date', models.DateField(blank=True, default='1399-04-01', null=True, verbose_name='Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QBesharat.Topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['description'],
                'unique_together': {('topic', 'description')},
            },
        ),
    ]
