# Generated by Django 3.0.6 on 2020-07-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QBesharat', '0011_auto_20200718_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['network', 'name'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterField(
            model_name='program',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QBesharat.Network', verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date',
            field=models.DateField(default='1399-04-01', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QBesharat.Topic', verbose_name='Topic'),
        ),
        migrations.CreateModel(
            name='Episod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(blank=True, default='1399-04-01', null=True, verbose_name='Publish Date')),
                ('duration', models.IntegerField(default=30, verbose_name='Duration (min)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QBesharat.Program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Episod',
                'verbose_name_plural': 'Episods',
                'ordering': ['publish_date'],
            },
        ),
    ]
