# Generated by Django 3.0.6 on 2020-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QBesharat', '0012_auto_20200718_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
    ]
