# Generated by Django 3.0.6 on 2020-07-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QBesharat', '0013_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True, verbose_name='URL')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QBesharat.Platform', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'EndPoint',
                'verbose_name_plural': 'EndPoint',
                'ordering': ['platform', 'url'],
            },
        ),
        migrations.AddField(
            model_name='episod',
            name='endpoints',
            field=models.ManyToManyField(to='QBesharat.EndPoint', verbose_name='EndPoints'),
        ),
    ]
