# Generated by Django 3.0.6 on 2020-07-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QBesharat', '0014_auto_20200718_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episod',
            name='endpoints',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='episod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='QBesharat.Episod', verbose_name='Episod'),
            preserve_default=False,
        ),
    ]
